/* ============================================================
 * This code is part of the "apex-lang" open source project avaiable at:
 * 
 *      http://code.google.com/p/apex-lang/
 *
 * This code is licensed under the Apache License, Version 2.0.  You may obtain a 
 * copy of the License at:
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * ============================================================
 */
global class NumberUtils {

	global static final Integer MAX_INTEGER = 2147483647;//Math.round(Math.pow(2.0,31.0)-1);
	global static final Integer MIN_INTEGER = -2147483647;//Math.round(Math.pow(2.0,31.0));
	
}