global enum Operator {

    //===============================
    // FIELD OPERATORS
    //===============================
    EQUALS,                   // =
    NOT_EQUALS,               // !=
    LESS_THAN,                // <
    LESS_THAN_OR_EQUAL_TO,    // <=
    GREATER_THAN,             // >
    GREATER_THAN_OR_EQUAL_TO, // >=
    LIKEX,                    // like
    
    //===============================
    // SET OPERATORS
    //===============================
    INCLUDES,                 // includes
    EXCLUDES,                 // excludes
    INX,                      // in
    NOT_IN                    // not in 

}